### ISSUE TITLE
class java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by JeeeXD** [Lymia/MPPatch#87]
I'm trying to get the MPPatch working but it isn't 

https://github.com/Lymia/MPPatch/releases/tag/ci_build-120 
This is the build I'm using. I'm on Linux Mint 
This also happened with all other builds I used with  the exact same error. I used versions 124,118 and 97 they all didn't work. I'm using the proton version of Civ 5 and I tried to use the AppImage and it gave me the same error and the exe didn't work at all.

Distributor ID: Linuxmint
Description:    Linux Mint 21.2
Release:        21.2
Codename:       victoria

```
MPPatch version 0.2.0-r4afbacc
Revision 4afbacca, built on Dec 19, 2023 by runner@fv-az1242-237 (Github Actions)

Build ID   : 3349b689-4089-4d18-8793-4789e36b02b6
Build Date : 2023-12-19T17:58:14Z
Revision   : 4afbacca5ac38960eeb80f3b63c3b6bb2337da09
Tree Status: <clean>
[2023-12-20T07:42:01Z/ INFO] Running from .jar
[2023-12-20T07:42:01Z/ INFO] Platform: linux
[2023-12-20T07:42:01Z/ INFO] Base directory: /home/jeee/Downloads

[2023-12-20T07:42:01Z/ INFO] Changing patch package...
[2023-12-20T07:42:08Z/ERROR] An unexpected error occured:
class java.util.NoSuchElementException: head of empty list
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:662)
        at scala.collection.immutable.Nil$.head(List.scala:661)
        at moe.lymia.mppatch.ui.LegacyMainFrame.<init>(LegacyMainFrame.scala:83)
        at moe.lymia.mppatch.ui.MPPatchInstaller$.main(MPPatchInstaller.scala:155)
        at moe.lymia.mppatch.ui.MPPatchInstaller.main(MPPatchInstaller.scala)

```
This is the error message I get. Please help

**Comment by Lymia** [comment]
The ci_build versions are not ready for release, they're pre-release only, I just don't know how to get Github to show the current release first.

Try the latest stable version: https://github.com/Lymia/MPPatch/releases/tag/v0.1.3

This happens because the development version currently doesn't know what to do when it can't find the Civ V installation. The stable version lets you select the directory.
